// The application SSR bundle is retained; this small entry owns Sites bindings.
// @ts-expect-error generated by the retained TanStack/Nitro build
import app from "./app/index.mjs";
import {handleApi,type Env} from "./api.ts";
export default {
  async fetch(request:Request,env:Env,ctx:unknown):Promise<Response>{
    if(new URL(request.url).pathname.startsWith("/api/sites/"))return handleApi(request,env);
    if(env.ASSETS){const asset=await env.ASSETS.fetch(request);if(asset.status!==404)return asset;}
    const response=await app.fetch(request,env,ctx);
    const headers=new Headers(response.headers);headers.set("Cache-Control","private, no-store");
    return new Response(response.body,{status:response.status,headers});
  },
};
