/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkoutsIndexRouteImport } from './routes/_authenticated/workouts/index'
import { Route as AuthenticatedWorkoutsNewRouteImport } from './routes/_authenticated/workouts/new'
import { Route as AuthenticatedWorkoutsTemplateIdRunRouteImport } from './routes/_authenticated/workouts/$templateId/run'
import { Route as AuthenticatedWorkoutsTemplateIdEditRouteImport } from './routes/_authenticated/workouts/$templateId/edit'
import { Route as AuthenticatedSessionsSessionIdSummaryRouteImport } from './routes/_authenticated/sessions/$sessionId/summary'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkoutsIndexRoute =
  AuthenticatedWorkoutsIndexRouteImport.update({
    id: '/workouts/',
    path: '/workouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsNewRoute =
  AuthenticatedWorkoutsNewRouteImport.update({
    id: '/workouts/new',
    path: '/workouts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsTemplateIdRunRoute =
  AuthenticatedWorkoutsTemplateIdRunRouteImport.update({
    id: '/workouts/$templateId/run',
    path: '/workouts/$templateId/run',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsTemplateIdEditRoute =
  AuthenticatedWorkoutsTemplateIdEditRouteImport.update({
    id: '/workouts/$templateId/edit',
    path: '/workouts/$templateId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdSummaryRoute =
  AuthenticatedSessionsSessionIdSummaryRouteImport.update({
    id: '/sessions/$sessionId/summary',
    path: '/sessions/$sessionId/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workouts/new': typeof AuthenticatedWorkoutsNewRoute
  '/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/sessions/$sessionId/summary': typeof AuthenticatedSessionsSessionIdSummaryRoute
  '/workouts/$templateId/edit': typeof AuthenticatedWorkoutsTemplateIdEditRoute
  '/workouts/$templateId/run': typeof AuthenticatedWorkoutsTemplateIdRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/workouts/new': typeof AuthenticatedWorkoutsNewRoute
  '/workouts': typeof AuthenticatedWorkoutsIndexRoute
  '/sessions/$sessionId/summary': typeof AuthenticatedSessionsSessionIdSummaryRoute
  '/workouts/$templateId/edit': typeof AuthenticatedWorkoutsTemplateIdEditRoute
  '/workouts/$templateId/run': typeof AuthenticatedWorkoutsTemplateIdRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/workouts/new': typeof AuthenticatedWorkoutsNewRoute
  '/_authenticated/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/_authenticated/sessions/$sessionId/summary': typeof AuthenticatedSessionsSessionIdSummaryRoute
  '/_authenticated/workouts/$templateId/edit': typeof AuthenticatedWorkoutsTemplateIdEditRoute
  '/_authenticated/workouts/$templateId/run': typeof AuthenticatedWorkoutsTemplateIdRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/workouts/new'
    | '/workouts/'
    | '/sessions/$sessionId/summary'
    | '/workouts/$templateId/edit'
    | '/workouts/$templateId/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/workouts/new'
    | '/workouts'
    | '/sessions/$sessionId/summary'
    | '/workouts/$templateId/edit'
    | '/workouts/$templateId/run'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/workouts/new'
    | '/_authenticated/workouts/'
    | '/_authenticated/sessions/$sessionId/summary'
    | '/_authenticated/workouts/$templateId/edit'
    | '/_authenticated/workouts/$templateId/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workouts/': {
      id: '/_authenticated/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthenticatedWorkoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/new': {
      id: '/_authenticated/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof AuthenticatedWorkoutsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/$templateId/run': {
      id: '/_authenticated/workouts/$templateId/run'
      path: '/workouts/$templateId/run'
      fullPath: '/workouts/$templateId/run'
      preLoaderRoute: typeof AuthenticatedWorkoutsTemplateIdRunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/$templateId/edit': {
      id: '/_authenticated/workouts/$templateId/edit'
      path: '/workouts/$templateId/edit'
      fullPath: '/workouts/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedWorkoutsTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId/summary': {
      id: '/_authenticated/sessions/$sessionId/summary'
      path: '/sessions/$sessionId/summary'
      fullPath: '/sessions/$sessionId/summary'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedWorkoutsNewRoute: typeof AuthenticatedWorkoutsNewRoute
  AuthenticatedWorkoutsIndexRoute: typeof AuthenticatedWorkoutsIndexRoute
  AuthenticatedSessionsSessionIdSummaryRoute: typeof AuthenticatedSessionsSessionIdSummaryRoute
  AuthenticatedWorkoutsTemplateIdEditRoute: typeof AuthenticatedWorkoutsTemplateIdEditRoute
  AuthenticatedWorkoutsTemplateIdRunRoute: typeof AuthenticatedWorkoutsTemplateIdRunRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedWorkoutsNewRoute: AuthenticatedWorkoutsNewRoute,
  AuthenticatedWorkoutsIndexRoute: AuthenticatedWorkoutsIndexRoute,
  AuthenticatedSessionsSessionIdSummaryRoute:
    AuthenticatedSessionsSessionIdSummaryRoute,
  AuthenticatedWorkoutsTemplateIdEditRoute:
    AuthenticatedWorkoutsTemplateIdEditRoute,
  AuthenticatedWorkoutsTemplateIdRunRoute:
    AuthenticatedWorkoutsTemplateIdRunRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
