/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedAthleticsRouteRouteImport } from './routes/_authenticated/athletics/route'
import { Route as AuthenticatedWorkoutsIndexRouteImport } from './routes/_authenticated/workouts/index'
import { Route as AuthenticatedAthleticsIndexRouteImport } from './routes/_authenticated/athletics/index'
import { Route as AuthenticatedWorkoutsNewRouteImport } from './routes/_authenticated/workouts/new'
import { Route as AuthenticatedProfileExportRouteImport } from './routes/_authenticated/profile/export'
import { Route as AuthenticatedAthleticsTestsRouteImport } from './routes/_authenticated/athletics/tests'
import { Route as AuthenticatedAthleticsRacesRouteImport } from './routes/_authenticated/athletics/races'
import { Route as AuthenticatedWorkoutsTemplateIdIndexRouteImport } from './routes/_authenticated/workouts/$templateId/index'
import { Route as AuthenticatedWorkoutsIntervalsNewRouteImport } from './routes/_authenticated/workouts/intervals/new'
import { Route as AuthenticatedWorkoutsTemplateIdRunRouteImport } from './routes/_authenticated/workouts/$templateId/run'
import { Route as AuthenticatedWorkoutsTemplateIdEditRouteImport } from './routes/_authenticated/workouts/$templateId/edit'
import { Route as AuthenticatedSessionsSessionIdSummaryRouteImport } from './routes/_authenticated/sessions/$sessionId/summary'
import { Route as AuthenticatedAthleticsTestsTypeIdRouteImport } from './routes/_authenticated/athletics/tests/$typeId'
import { Route as AuthenticatedAthleticsRacesNewRouteImport } from './routes/_authenticated/athletics/races/new'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAthleticsRouteRoute =
  AuthenticatedAthleticsRouteRouteImport.update({
    id: '/athletics',
    path: '/athletics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsIndexRoute =
  AuthenticatedWorkoutsIndexRouteImport.update({
    id: '/workouts/',
    path: '/workouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthleticsIndexRoute =
  AuthenticatedAthleticsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAthleticsRouteRoute,
  } as any)
const AuthenticatedWorkoutsNewRoute =
  AuthenticatedWorkoutsNewRouteImport.update({
    id: '/workouts/new',
    path: '/workouts/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileExportRoute =
  AuthenticatedProfileExportRouteImport.update({
    id: '/export',
    path: '/export',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedAthleticsTestsRoute =
  AuthenticatedAthleticsTestsRouteImport.update({
    id: '/tests',
    path: '/tests',
    getParentRoute: () => AuthenticatedAthleticsRouteRoute,
  } as any)
const AuthenticatedAthleticsRacesRoute =
  AuthenticatedAthleticsRacesRouteImport.update({
    id: '/races',
    path: '/races',
    getParentRoute: () => AuthenticatedAthleticsRouteRoute,
  } as any)
const AuthenticatedWorkoutsTemplateIdIndexRoute =
  AuthenticatedWorkoutsTemplateIdIndexRouteImport.update({
    id: '/workouts/$templateId/',
    path: '/workouts/$templateId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsIntervalsNewRoute =
  AuthenticatedWorkoutsIntervalsNewRouteImport.update({
    id: '/workouts/intervals/new',
    path: '/workouts/intervals/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsTemplateIdRunRoute =
  AuthenticatedWorkoutsTemplateIdRunRouteImport.update({
    id: '/workouts/$templateId/run',
    path: '/workouts/$templateId/run',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkoutsTemplateIdEditRoute =
  AuthenticatedWorkoutsTemplateIdEditRouteImport.update({
    id: '/workouts/$templateId/edit',
    path: '/workouts/$templateId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSessionsSessionIdSummaryRoute =
  AuthenticatedSessionsSessionIdSummaryRouteImport.update({
    id: '/sessions/$sessionId/summary',
    path: '/sessions/$sessionId/summary',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAthleticsTestsTypeIdRoute =
  AuthenticatedAthleticsTestsTypeIdRouteImport.update({
    id: '/$typeId',
    path: '/$typeId',
    getParentRoute: () => AuthenticatedAthleticsTestsRoute,
  } as any)
const AuthenticatedAthleticsRacesNewRoute =
  AuthenticatedAthleticsRacesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAthleticsRacesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/athletics': typeof AuthenticatedAthleticsRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/athletics/races': typeof AuthenticatedAthleticsRacesRouteWithChildren
  '/athletics/tests': typeof AuthenticatedAthleticsTestsRouteWithChildren
  '/profile/export': typeof AuthenticatedProfileExportRoute
  '/workouts/new': typeof AuthenticatedWorkoutsNewRoute
  '/athletics/': typeof AuthenticatedAthleticsIndexRoute
  '/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/athletics/races/new': typeof AuthenticatedAthleticsRacesNewRoute
  '/athletics/tests/$typeId': typeof AuthenticatedAthleticsTestsTypeIdRoute
  '/sessions/$sessionId/summary': typeof AuthenticatedSessionsSessionIdSummaryRoute
  '/workouts/$templateId/edit': typeof AuthenticatedWorkoutsTemplateIdEditRoute
  '/workouts/$templateId/run': typeof AuthenticatedWorkoutsTemplateIdRunRoute
  '/workouts/intervals/new': typeof AuthenticatedWorkoutsIntervalsNewRoute
  '/workouts/$templateId/': typeof AuthenticatedWorkoutsTemplateIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/athletics/races': typeof AuthenticatedAthleticsRacesRouteWithChildren
  '/athletics/tests': typeof AuthenticatedAthleticsTestsRouteWithChildren
  '/profile/export': typeof AuthenticatedProfileExportRoute
  '/workouts/new': typeof AuthenticatedWorkoutsNewRoute
  '/athletics': typeof AuthenticatedAthleticsIndexRoute
  '/workouts': typeof AuthenticatedWorkoutsIndexRoute
  '/athletics/races/new': typeof AuthenticatedAthleticsRacesNewRoute
  '/athletics/tests/$typeId': typeof AuthenticatedAthleticsTestsTypeIdRoute
  '/sessions/$sessionId/summary': typeof AuthenticatedSessionsSessionIdSummaryRoute
  '/workouts/$templateId/edit': typeof AuthenticatedWorkoutsTemplateIdEditRoute
  '/workouts/$templateId/run': typeof AuthenticatedWorkoutsTemplateIdRunRoute
  '/workouts/intervals/new': typeof AuthenticatedWorkoutsIntervalsNewRoute
  '/workouts/$templateId': typeof AuthenticatedWorkoutsTemplateIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/athletics': typeof AuthenticatedAthleticsRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/athletics/races': typeof AuthenticatedAthleticsRacesRouteWithChildren
  '/_authenticated/athletics/tests': typeof AuthenticatedAthleticsTestsRouteWithChildren
  '/_authenticated/profile/export': typeof AuthenticatedProfileExportRoute
  '/_authenticated/workouts/new': typeof AuthenticatedWorkoutsNewRoute
  '/_authenticated/athletics/': typeof AuthenticatedAthleticsIndexRoute
  '/_authenticated/workouts/': typeof AuthenticatedWorkoutsIndexRoute
  '/_authenticated/athletics/races/new': typeof AuthenticatedAthleticsRacesNewRoute
  '/_authenticated/athletics/tests/$typeId': typeof AuthenticatedAthleticsTestsTypeIdRoute
  '/_authenticated/sessions/$sessionId/summary': typeof AuthenticatedSessionsSessionIdSummaryRoute
  '/_authenticated/workouts/$templateId/edit': typeof AuthenticatedWorkoutsTemplateIdEditRoute
  '/_authenticated/workouts/$templateId/run': typeof AuthenticatedWorkoutsTemplateIdRunRoute
  '/_authenticated/workouts/intervals/new': typeof AuthenticatedWorkoutsIntervalsNewRoute
  '/_authenticated/workouts/$templateId/': typeof AuthenticatedWorkoutsTemplateIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/athletics'
    | '/home'
    | '/profile'
    | '/athletics/races'
    | '/athletics/tests'
    | '/profile/export'
    | '/workouts/new'
    | '/athletics/'
    | '/workouts/'
    | '/athletics/races/new'
    | '/athletics/tests/$typeId'
    | '/sessions/$sessionId/summary'
    | '/workouts/$templateId/edit'
    | '/workouts/$templateId/run'
    | '/workouts/intervals/new'
    | '/workouts/$templateId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/home'
    | '/profile'
    | '/athletics/races'
    | '/athletics/tests'
    | '/profile/export'
    | '/workouts/new'
    | '/athletics'
    | '/workouts'
    | '/athletics/races/new'
    | '/athletics/tests/$typeId'
    | '/sessions/$sessionId/summary'
    | '/workouts/$templateId/edit'
    | '/workouts/$templateId/run'
    | '/workouts/intervals/new'
    | '/workouts/$templateId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/athletics'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/athletics/races'
    | '/_authenticated/athletics/tests'
    | '/_authenticated/profile/export'
    | '/_authenticated/workouts/new'
    | '/_authenticated/athletics/'
    | '/_authenticated/workouts/'
    | '/_authenticated/athletics/races/new'
    | '/_authenticated/athletics/tests/$typeId'
    | '/_authenticated/sessions/$sessionId/summary'
    | '/_authenticated/workouts/$templateId/edit'
    | '/_authenticated/workouts/$templateId/run'
    | '/_authenticated/workouts/intervals/new'
    | '/_authenticated/workouts/$templateId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletics': {
      id: '/_authenticated/athletics'
      path: '/athletics'
      fullPath: '/athletics'
      preLoaderRoute: typeof AuthenticatedAthleticsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/': {
      id: '/_authenticated/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof AuthenticatedWorkoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletics/': {
      id: '/_authenticated/athletics/'
      path: '/'
      fullPath: '/athletics/'
      preLoaderRoute: typeof AuthenticatedAthleticsIndexRouteImport
      parentRoute: typeof AuthenticatedAthleticsRouteRoute
    }
    '/_authenticated/workouts/new': {
      id: '/_authenticated/workouts/new'
      path: '/workouts/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof AuthenticatedWorkoutsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/export': {
      id: '/_authenticated/profile/export'
      path: '/export'
      fullPath: '/profile/export'
      preLoaderRoute: typeof AuthenticatedProfileExportRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/athletics/tests': {
      id: '/_authenticated/athletics/tests'
      path: '/tests'
      fullPath: '/athletics/tests'
      preLoaderRoute: typeof AuthenticatedAthleticsTestsRouteImport
      parentRoute: typeof AuthenticatedAthleticsRouteRoute
    }
    '/_authenticated/athletics/races': {
      id: '/_authenticated/athletics/races'
      path: '/races'
      fullPath: '/athletics/races'
      preLoaderRoute: typeof AuthenticatedAthleticsRacesRouteImport
      parentRoute: typeof AuthenticatedAthleticsRouteRoute
    }
    '/_authenticated/workouts/$templateId/': {
      id: '/_authenticated/workouts/$templateId/'
      path: '/workouts/$templateId'
      fullPath: '/workouts/$templateId/'
      preLoaderRoute: typeof AuthenticatedWorkoutsTemplateIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/intervals/new': {
      id: '/_authenticated/workouts/intervals/new'
      path: '/workouts/intervals/new'
      fullPath: '/workouts/intervals/new'
      preLoaderRoute: typeof AuthenticatedWorkoutsIntervalsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/$templateId/run': {
      id: '/_authenticated/workouts/$templateId/run'
      path: '/workouts/$templateId/run'
      fullPath: '/workouts/$templateId/run'
      preLoaderRoute: typeof AuthenticatedWorkoutsTemplateIdRunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts/$templateId/edit': {
      id: '/_authenticated/workouts/$templateId/edit'
      path: '/workouts/$templateId/edit'
      fullPath: '/workouts/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedWorkoutsTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sessions/$sessionId/summary': {
      id: '/_authenticated/sessions/$sessionId/summary'
      path: '/sessions/$sessionId/summary'
      fullPath: '/sessions/$sessionId/summary'
      preLoaderRoute: typeof AuthenticatedSessionsSessionIdSummaryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/athletics/tests/$typeId': {
      id: '/_authenticated/athletics/tests/$typeId'
      path: '/$typeId'
      fullPath: '/athletics/tests/$typeId'
      preLoaderRoute: typeof AuthenticatedAthleticsTestsTypeIdRouteImport
      parentRoute: typeof AuthenticatedAthleticsTestsRoute
    }
    '/_authenticated/athletics/races/new': {
      id: '/_authenticated/athletics/races/new'
      path: '/new'
      fullPath: '/athletics/races/new'
      preLoaderRoute: typeof AuthenticatedAthleticsRacesNewRouteImport
      parentRoute: typeof AuthenticatedAthleticsRacesRoute
    }
  }
}

interface AuthenticatedAthleticsRacesRouteChildren {
  AuthenticatedAthleticsRacesNewRoute: typeof AuthenticatedAthleticsRacesNewRoute
}

const AuthenticatedAthleticsRacesRouteChildren: AuthenticatedAthleticsRacesRouteChildren =
  {
    AuthenticatedAthleticsRacesNewRoute: AuthenticatedAthleticsRacesNewRoute,
  }

const AuthenticatedAthleticsRacesRouteWithChildren =
  AuthenticatedAthleticsRacesRoute._addFileChildren(
    AuthenticatedAthleticsRacesRouteChildren,
  )

interface AuthenticatedAthleticsTestsRouteChildren {
  AuthenticatedAthleticsTestsTypeIdRoute: typeof AuthenticatedAthleticsTestsTypeIdRoute
}

const AuthenticatedAthleticsTestsRouteChildren: AuthenticatedAthleticsTestsRouteChildren =
  {
    AuthenticatedAthleticsTestsTypeIdRoute:
      AuthenticatedAthleticsTestsTypeIdRoute,
  }

const AuthenticatedAthleticsTestsRouteWithChildren =
  AuthenticatedAthleticsTestsRoute._addFileChildren(
    AuthenticatedAthleticsTestsRouteChildren,
  )

interface AuthenticatedAthleticsRouteRouteChildren {
  AuthenticatedAthleticsRacesRoute: typeof AuthenticatedAthleticsRacesRouteWithChildren
  AuthenticatedAthleticsTestsRoute: typeof AuthenticatedAthleticsTestsRouteWithChildren
  AuthenticatedAthleticsIndexRoute: typeof AuthenticatedAthleticsIndexRoute
}

const AuthenticatedAthleticsRouteRouteChildren: AuthenticatedAthleticsRouteRouteChildren =
  {
    AuthenticatedAthleticsRacesRoute:
      AuthenticatedAthleticsRacesRouteWithChildren,
    AuthenticatedAthleticsTestsRoute:
      AuthenticatedAthleticsTestsRouteWithChildren,
    AuthenticatedAthleticsIndexRoute: AuthenticatedAthleticsIndexRoute,
  }

const AuthenticatedAthleticsRouteRouteWithChildren =
  AuthenticatedAthleticsRouteRoute._addFileChildren(
    AuthenticatedAthleticsRouteRouteChildren,
  )

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileExportRoute: typeof AuthenticatedProfileExportRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileExportRoute: AuthenticatedProfileExportRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAthleticsRouteRoute: typeof AuthenticatedAthleticsRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedWorkoutsNewRoute: typeof AuthenticatedWorkoutsNewRoute
  AuthenticatedWorkoutsIndexRoute: typeof AuthenticatedWorkoutsIndexRoute
  AuthenticatedSessionsSessionIdSummaryRoute: typeof AuthenticatedSessionsSessionIdSummaryRoute
  AuthenticatedWorkoutsTemplateIdEditRoute: typeof AuthenticatedWorkoutsTemplateIdEditRoute
  AuthenticatedWorkoutsTemplateIdRunRoute: typeof AuthenticatedWorkoutsTemplateIdRunRoute
  AuthenticatedWorkoutsIntervalsNewRoute: typeof AuthenticatedWorkoutsIntervalsNewRoute
  AuthenticatedWorkoutsTemplateIdIndexRoute: typeof AuthenticatedWorkoutsTemplateIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAthleticsRouteRoute:
    AuthenticatedAthleticsRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedWorkoutsNewRoute: AuthenticatedWorkoutsNewRoute,
  AuthenticatedWorkoutsIndexRoute: AuthenticatedWorkoutsIndexRoute,
  AuthenticatedSessionsSessionIdSummaryRoute:
    AuthenticatedSessionsSessionIdSummaryRoute,
  AuthenticatedWorkoutsTemplateIdEditRoute:
    AuthenticatedWorkoutsTemplateIdEditRoute,
  AuthenticatedWorkoutsTemplateIdRunRoute:
    AuthenticatedWorkoutsTemplateIdRunRoute,
  AuthenticatedWorkoutsIntervalsNewRoute:
    AuthenticatedWorkoutsIntervalsNewRoute,
  AuthenticatedWorkoutsTemplateIdIndexRoute:
    AuthenticatedWorkoutsTemplateIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
