-- Catalogo esteso core, running e varianti unilaterali.
-- I nomi duplicati della lista sorgente sono deduplicati case-insensitivamente.
INSERT INTO public.exercises (name, muscle_group, equipment, category, is_default) VALUES
  ('Plank sui gomiti','Core','Corpo libero','Core',true),
  ('Plank alto','Core','Corpo libero','Core',true),
  ('Plank con ginocchia appoggiate','Core','Corpo libero','Core',true),
  ('RKC Plank','Core','Corpo libero','Core',true),
  ('Body Saw','Core','Corpo libero','Core',true),
  ('Long-Lever Plank','Core','Corpo libero','Core',true),
  ('Plank con sollevamento gamba','Core','Corpo libero','Core',true),
  ('Plank con sollevamento braccio','Core','Corpo libero','Core',true),
  ('Plank Bird Dog','Core','Corpo libero','Core',true),
  ('Plank Walkout','Core','Corpo libero','Core',true),
  ('Ab Wheel Rollout','Core','Corpo libero','Core',true),
  ('Rollout con bilanciere','Core','Bilanciere','Core',true),
  ('Rollout su fitball','Core','Palla','Core',true),
  ('Stir the Pot','Core','Corpo libero','Core',true),
  ('Dead Bug','Core','Corpo libero','Core',true),
  ('Dead Bug con elastico','Core','Elastico','Core',true),
  ('Dead Bug con palla','Core','Palla','Core',true),
  ('Hollow Body Hold','Core','Corpo libero','Core',true),
  ('Hollow Body Rock','Core','Corpo libero','Core',true),
  ('Bear Plank','Core','Corpo libero','Core',true),
  ('Bear Crawl','Core','Corpo libero','Core',true),
  ('Mountain Climber controllato','Core','Corpo libero','Core',true),
  ('Pallof Press','Core','Corpo libero','Core',true),
  ('Pallof Press isometrica','Core','Corpo libero','Core',true),
  ('Pallof Press in ginocchio','Core','Corpo libero','Core',true),
  ('Pallof Press mezzo inginocchio','Core','Corpo libero','Core',true),
  ('Pallof Press sopra la testa','Core','Corpo libero','Core',true),
  ('Pallof Walkout','Core','Corpo libero','Core',true),
  ('Plank con trascinamento del peso','Core','Corpo libero','Core',true),
  ('Renegade Row','Core','Corpo libero','Core',true),
  ('Bird Dog','Core','Corpo libero','Core',true),
  ('Bird Dog Row','Core','Corpo libero','Core',true),
  ('Shoulder Tap','Core','Corpo libero','Core',true),
  ('Bear Plank Shoulder Tap','Core','Corpo libero','Core',true),
  ('Suitcase Carry','Core','Corpo libero','Core',true),
  ('Offset Farmer Carry','Core','Corpo libero','Core',true),
  ('Single-Arm Farmer Carry','Core','Corpo libero','Core',true),
  ('Single-Arm Front Rack Carry','Core','Corpo libero','Core',true),
  ('Side Plank','Core','Corpo libero','Core',true),
  ('Side Plank con ginocchia appoggiate','Core','Corpo libero','Core',true),
  ('Side Plank sui piedi','Core','Corpo libero','Core',true),
  ('Side Plank con abduzione della gamba','Core','Corpo libero','Core',true),
  ('Side Plank Star','Core','Corpo libero','Core',true),
  ('Copenhagen Plank','Core','Corpo libero','Core',true),
  ('Copenhagen Plank facilitato','Core','Corpo libero','Core',true),
  ('Waiter Carry a un braccio','Core','Corpo libero','Core',true),
  ('Farmer Carry asimmetrico','Core','Corpo libero','Core',true),
  ('Marcia con kettlebell sopra la testa','Core','Kettlebell','Core',true),
  ('Crunch','Core','Corpo libero','Core',true),
  ('Crunch a terra','Core','Corpo libero','Core',true),
  ('Crunch su fitball','Core','Palla','Core',true),
  ('Crunch al cavo','Core','Cavi','Core',true),
  ('Crunch alla macchina','Core','Corpo libero','Core',true),
  ('Reverse Crunch','Core','Corpo libero','Core',true),
  ('Bicycle Crunch','Core','Corpo libero','Core',true),
  ('Toe Touch','Core','Corpo libero','Core',true),
  ('Sit-up','Core','Corpo libero','Core',true),
  ('Sit-up con peso','Core','Corpo libero','Core',true),
  ('Butterfly Sit-up','Core','Corpo libero','Core',true),
  ('V-up','Core','Corpo libero','Core',true),
  ('Tuck-up','Core','Corpo libero','Core',true),
  ('Jackknife','Core','Corpo libero','Core',true),
  ('Candlestick','Core','Corpo libero','Core',true),
  ('Garhammer Raise','Core','Corpo libero','Core',true),
  ('Russian Twist','Core','Corpo libero','Core',true),
  ('Cable Woodchop alto-basso','Core','Cavi','Core',true),
  ('Cable Woodchop basso-alto','Core','Cavi','Core',true),
  ('Rotazioni al cavo','Core','Cavi','Core',true),
  ('Landmine Rotation','Core','Corpo libero','Core',true),
  ('Landmine Rainbow','Core','Corpo libero','Core',true),
  ('Medicine Ball Rotational Throw','Core','Palla','Core',true),
  ('Medicine Ball Side Throw','Core','Palla','Core',true),
  ('Cross-Body Mountain Climber','Core','Corpo libero','Core',true),
  ('Windshield Wiper','Core','Corpo libero','Core',true),
  ('Hanging Windshield Wiper','Core','Corpo libero','Core',true),
  ('Leg Raise a terra','Core','Corpo libero','Forza',true),
  ('Leg Raise su panca','Core','Corpo libero','Forza',true),
  ('Hanging Knee Raise','Core','Corpo libero','Forza',true),
  ('Hanging Leg Raise','Core','Corpo libero','Forza',true),
  ('Captain’s Chair Knee Raise','Core','Corpo libero','Forza',true),
  ('Captain’s Chair Leg Raise','Core','Corpo libero','Forza',true),
  ('Toes to Bar','Core','Corpo libero','Forza',true),
  ('L-Sit','Core','Corpo libero','Forza',true),
  ('L-Sit facilitato','Core','Corpo libero','Forza',true),
  ('Flutter Kick','Core','Corpo libero','Forza',true),
  ('Scissor Kick','Core','Corpo libero','Forza',true),
  ('Heel Tap','Core','Corpo libero','Forza',true),
  ('Glute Bridge','Glutei','Corpo libero','Core',true),
  ('Single-Leg Glute Bridge','Glutei','Corpo libero','Core',true),
  ('Hip Thrust','Glutei','Corpo libero','Core',true),
  ('Quadrupedia con estensione alternata','Core','Corpo libero','Core',true),
  ('Superman','Core','Corpo libero','Core',true),
  ('Swimmer','Core','Corpo libero','Core',true),
  ('Back Extension','Core','Corpo libero','Core',true),
  ('Hyperextension','Core','Corpo libero','Core',true),
  ('Reverse Hyperextension','Core','Corpo libero','Core',true),
  ('Good Morning isometrico','Gambe','Corpo libero','Core',true),
  ('Hip Hinge isometrico','Gambe','Corpo libero','Core',true),
  ('Pelvic Tilt','Core','Corpo libero','Core',true),
  ('Marcia in ponte','Glutei','Corpo libero','Core',true),
  ('Clamshell','Glutei','Corpo libero','Core',true),
  ('Side-Lying Hip Abduction','Glutei','Corpo libero','Core',true),
  ('Farmer Carry','Core','Corpo libero','Core',true),
  ('Front Rack Carry','Core','Corpo libero','Core',true),
  ('Waiter Carry','Core','Corpo libero','Core',true),
  ('Overhead Carry','Core','Corpo libero','Core',true),
  ('Zercher Carry','Core','Corpo libero','Core',true),
  ('Sled Push','Core','Slitta','Core',true),
  ('Sled Pull','Core','Slitta','Core',true),
  ('Crab Walk','Core','Corpo libero','Core',true),
  ('Leopard Crawl','Core','Corpo libero','Core',true),
  ('Inchworm','Core','Corpo libero','Core',true),
  ('Turkish Get-Up','Core','Corpo libero','Core',true),
  ('Kettlebell Swing','Core','Kettlebell','Core',true),
  ('Slam Ball','Core','Palla','Core',true),
  ('Medicine Ball Slam','Petto','Palla','Core',true),
  ('Battle Rope','Core','Corpo libero','Core',true),
  ('Rope Climb','Core','Corpo libero','Core',true),
  ('Squat Jump','Gambe','Corpo libero','Pliometria',true),
  ('Countermovement Jump','Atletica','Corpo libero','Pliometria',true),
  ('Tuck Jump','Atletica','Corpo libero','Pliometria',true),
  ('Vertical Jump','Atletica','Corpo libero','Pliometria',true),
  ('Jump and Reach','Atletica','Corpo libero','Pliometria',true),
  ('Pogo Jump','Caviglia','Corpo libero','Pliometria',true),
  ('Ankle Hop','Caviglia','Corpo libero','Pliometria',true),
  ('Rocket Jump','Atletica','Corpo libero','Pliometria',true),
  ('Star Jump','Atletica','Corpo libero','Pliometria',true),
  ('Split Squat Jump','Gambe','Corpo libero','Pliometria',true),
  ('Jumping Lunge','Gambe','Corpo libero','Pliometria',true),
  ('Scissor Jump','Atletica','Corpo libero','Pliometria',true),
  ('Knee-Tuck Jump','Atletica','Corpo libero','Pliometria',true),
  ('Depth Jump','Atletica','Corpo libero','Pliometria',true),
  ('Drop Jump','Atletica','Corpo libero','Pliometria',true),
  ('Seated Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('Weighted Jump Squat','Gambe','Corpo libero','Pliometria',true),
  ('Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('Low Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('High Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('Step-Up Jump','Gambe','Corpo libero','Pliometria',true),
  ('Lateral Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('Single-Leg Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('Depth Jump to Box','Atletica','Box/ostacoli','Pliometria',true),
  ('Box Jump con rincorsa','Gambe','Box/ostacoli','Pliometria',true),
  ('Box Jump Over','Gambe','Box/ostacoli','Pliometria',true),
  ('Burpee Box Jump','Gambe','Box/ostacoli','Pliometria',true),
  ('Box Jump Down controllato','Gambe','Box/ostacoli','Pliometria',true),
  ('Broad Jump','Atletica','Corpo libero','Pliometria',true),
  ('Standing Long Jump','Atletica','Corpo libero','Pliometria',true),
  ('Triple Broad Jump','Atletica','Corpo libero','Pliometria',true),
  ('Consecutive Broad Jump','Atletica','Corpo libero','Pliometria',true),
  ('Frog Jump','Atletica','Corpo libero','Pliometria',true),
  ('Bounds','Atletica','Corpo libero','Pliometria',true),
  ('Alternate Bounds','Atletica','Corpo libero','Pliometria',true),
  ('Single-Leg Bound','Atletica','Corpo libero','Pliometria',true),
  ('Hop and Stick','Atletica','Corpo libero','Pliometria',true),
  ('Triple Hop','Atletica','Corpo libero','Pliometria',true),
  ('Crossover Hop','Atletica','Corpo libero','Pliometria',true),
  ('Skater Jump','Atletica','Corpo libero','Pliometria',true),
  ('Lateral Bound','Atletica','Corpo libero','Pliometria',true),
  ('Single-Leg Hop','Atletica','Corpo libero','Pliometria',true),
  ('Single-Leg Pogo','Caviglia','Corpo libero','Pliometria',true),
  ('Forward Hop','Atletica','Corpo libero','Pliometria',true),
  ('Backward Hop','Atletica','Corpo libero','Pliometria',true),
  ('Lateral Hop','Atletica','Corpo libero','Pliometria',true),
  ('Diagonal Hop','Atletica','Corpo libero','Pliometria',true),
  ('Hurdle Hop monopodalico','Atletica','Box/ostacoli','Pliometria',true),
  ('Hop and Hold','Atletica','Corpo libero','Pliometria',true),
  ('Single-Leg Broad Jump','Atletica','Corpo libero','Pliometria',true),
  ('Single-Leg Depth Jump','Atletica','Corpo libero','Pliometria',true),
  ('Hurdle Jump','Atletica','Box/ostacoli','Pliometria',true),
  ('Consecutive Hurdle Jump','Atletica','Box/ostacoli','Pliometria',true),
  ('Lateral Hurdle Hop','Atletica','Box/ostacoli','Pliometria',true),
  ('Forward-Backward Hurdle Hop','Atletica','Box/ostacoli','Pliometria',true),
  ('Single-Leg Hurdle Hop','Atletica','Box/ostacoli','Pliometria',true),
  ('Depth Jump oltre ostacolo','Atletica','Box/ostacoli','Pliometria',true),
  ('Zig-Zag Hurdle Jump','Atletica','Box/ostacoli','Pliometria',true),
  ('Quick Hurdle Hop','Atletica','Box/ostacoli','Pliometria',true),
  ('Line Hop','Atletica','Corpo libero','Pliometria',true),
  ('Jump Rope','Caviglia','Corpo libero','Pliometria',true),
  ('Fast Feet','Atletica','Corpo libero','Pliometria',true),
  ('Ankle Bounce','Caviglia','Corpo libero','Pliometria',true),
  ('Reactive Drop Jump','Atletica','Corpo libero','Pliometria',true),
  ('Quick Ground Contact Jump','Atletica','Corpo libero','Pliometria',true),
  ('Mini-Hurdle Hop','Atletica','Box/ostacoli','Pliometria',true),
  ('Lateral Line Hop','Atletica','Corpo libero','Pliometria',true),
  ('Alternating Pogo','Caviglia','Corpo libero','Pliometria',true),
  ('Plyometric Push-Up','Petto','Corpo libero','Pliometria',true),
  ('Clap Push-Up','Petto','Corpo libero','Pliometria',true),
  ('Depth Push-Up','Petto','Corpo libero','Pliometria',true),
  ('Explosive Incline Push-Up','Petto','Corpo libero','Pliometria',true),
  ('Medicine Ball Chest Pass','Petto','Palla','Pliometria',true),
  ('Medicine Ball Overhead Throw','Petto','Palla','Pliometria',true),
  ('Rotational Medicine Ball Throw','Atletica','Palla','Pliometria',true),
  ('Scoop Toss','Petto','Corpo libero','Pliometria',true),
  ('Shot-Put Throw','Petto','Corpo libero','Pliometria',true),
  ('Explosive Wall Pass','Petto','Corpo libero','Pliometria',true),
  ('Corsa facile','Cardio','Corpo libero','Corsa',true),
  ('Corsa lenta','Cardio','Corpo libero','Corsa',true),
  ('Corsa di recupero','Cardio','Corpo libero','Corsa',true),
  ('Corsa aerobica','Cardio','Corpo libero','Corsa',true),
  ('Corsa continua','Cardio','Corpo libero','Corsa',true),
  ('Fondo lento','Cardio','Corpo libero','Corsa',true),
  ('Fondo medio','Cardio','Corpo libero','Corsa',true),
  ('Fondo lungo','Cardio','Corpo libero','Corsa',true),
  ('Corsa lunga progressiva','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo medio','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo sostenuto','Cardio','Corpo libero','Corsa',true),
  ('Corsa progressiva','Cardio','Corpo libero','Corsa',true),
  ('Corsa regressiva','Cardio','Corpo libero','Corsa',true),
  ('Corsa a variazioni','Cardio','Corpo libero','Corsa',true),
  ('Fartlek','Cardio','Corpo libero','Corsa',true),
  ('Tempo Run','Cardio','Corpo libero','Corsa',true),
  ('Threshold Run','Cardio','Corpo libero','Corsa',true),
  ('Corsa alla soglia','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo gara','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo maratona','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo mezza maratona','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo 10 km','Cardio','Corpo libero','Corsa',true),
  ('Corsa a ritmo 5 km','Cardio','Corpo libero','Corsa',true),
  ('Test cronometrato','Cardio','Corpo libero','Corsa',true),
  ('Time Trial','Cardio','Corpo libero','Corsa',true),
  ('Cooper Test','Cardio','Corpo libero','Corsa',true),
  ('Corsa-camminata','Cardio','Corpo libero','Corsa',true),
  ('Jogging','Cardio','Corpo libero','Corsa',true),
  ('Trail Running','Cardio','Corpo libero','Corsa',true),
  ('Cross-Country','Cardio','Corpo libero','Corsa',true),
  ('Corsa su tapis roulant','Cardio','Corpo libero','Corsa',true),
  ('Corsa sulla sabbia','Cardio','Corpo libero','Corsa',true),
  ('Corsa in acqua','Cardio','Corpo libero','Corsa',true),
  ('Corsa con passeggino','Cardio','Corpo libero','Corsa',true),
  ('Corsa con zavorra','Cardio','Corpo libero','Corsa',true),
  ('Ripetute brevi','Cardio','Corpo libero','Corsa',true),
  ('Ripetute medie','Cardio','Corpo libero','Corsa',true),
  ('Ripetute lunghe','Cardio','Corpo libero','Corsa',true),
  ('Intervalli aerobici','Cardio','Corpo libero','Corsa',true),
  ('Intervalli anaerobici','Cardio','Corpo libero','Corsa',true),
  ('Interval Training','Cardio','Corpo libero','Corsa',true),
  ('High-Intensity Interval Running','Cardio','Corpo libero','Corsa',true),
  ('Sprint Interval Training','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 50 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 100 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 200 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 300 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 400 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 500 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 800 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 1.000 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 1.200 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 1.600 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 2.000 metri','Cardio','Corpo libero','Corsa',true),
  ('Ripetute da 3.000 metri','Cardio','Corpo libero','Corsa',true),
  ('Intervalli a tempo','Cardio','Corpo libero','Corsa',true),
  ('Intervalli piramidali','Cardio','Corpo libero','Corsa',true),
  ('Intervalli a scala','Cardio','Corpo libero','Corsa',true),
  ('Intervalli misti','Cardio','Corpo libero','Corsa',true),
  ('Intervalli decrescenti','Cardio','Corpo libero','Corsa',true),
  ('Intervalli progressivi','Cardio','Corpo libero','Corsa',true),
  ('Yasso 800','Cardio','Corpo libero','Corsa',true),
  ('Billat 30-30','Cardio','Corpo libero','Corsa',true),
  ('Intervalli 60-60','Cardio','Corpo libero','Corsa',true),
  ('Intervalli 4 × 4 minuti','Cardio','Corpo libero','Corsa',true),
  ('Sprint 10 metri','Cardio','Corpo libero','Corsa',true),
  ('Sprint 20 metri','Cardio','Corpo libero','Corsa',true),
  ('Sprint 30 metri','Cardio','Corpo libero','Corsa',true),
  ('Sprint 40 metri','Cardio','Corpo libero','Corsa',true),
  ('Sprint 60 metri','Cardio','Corpo libero','Corsa',true),
  ('Sprint 80 metri','Cardio','Corpo libero','Corsa',true),
  ('Sprint 100 metri','Cardio','Corpo libero','Corsa',true),
  ('Flying Sprint','Cardio','Corpo libero','Corsa',true),
  ('Sprint con partenza da fermo','Cardio','Corpo libero','Corsa',true),
  ('Sprint con partenza lanciata','Cardio','Corpo libero','Corsa',true),
  ('Sprint in salita','Cardio','Corpo libero','Corsa',true),
  ('Sprint in discesa controllata','Cardio','Corpo libero','Corsa',true),
  ('Sprint resistito','Cardio','Corpo libero','Corsa',true),
  ('Sprint con slitta','Cardio','Slitta','Corsa',true),
  ('Sprint con elastico','Cardio','Elastico','Corsa',true),
  ('Sprint assistito','Cardio','Corpo libero','Corsa',true),
  ('Sprint ripetuti','Cardio','Corpo libero','Corsa',true),
  ('Shuttle Sprint','Cardio','Corpo libero','Corsa',true),
  ('Sprint con cambio di direzione','Cardio','Corpo libero','Corsa',true),
  ('Ripetute brevi in salita','Cardio','Corpo libero','Corsa',true),
  ('Ripetute lunghe in salita','Cardio','Corpo libero','Corsa',true),
  ('Hill Repeats','Cardio','Corpo libero','Corsa',true),
  ('Hill Bounds','Cardio','Corpo libero','Corsa',true),
  ('Corsa continua collinare','Cardio','Corpo libero','Corsa',true),
  ('Fartlek collinare','Cardio','Corpo libero','Corsa',true),
  ('Salita a ritmo soglia','Cardio','Corpo libero','Corsa',true),
  ('Corsa su gradini','Cardio','Corpo libero','Corsa',true),
  ('Power Hiking','Cardio','Corpo libero','Corsa',true),
  ('Salita su tapis roulant','Cardio','Corpo libero','Corsa',true),
  ('Marcia tecnica','Cardio','Corpo libero','Corsa',true),
  ('A-March','Cardio','Corpo libero','Corsa',true),
  ('A-Skip','Cardio','Corpo libero','Corsa',true),
  ('B-Skip','Cardio','Corpo libero','Corsa',true),
  ('C-Skip','Cardio','Corpo libero','Corsa',true),
  ('Skip basso','Cardio','Corpo libero','Corsa',true),
  ('Skip medio','Cardio','Corpo libero','Corsa',true),
  ('Skip alto','Cardio','Corpo libero','Corsa',true),
  ('High Knees','Cardio','Corpo libero','Corsa',true),
  ('Calciata dietro','Cardio','Corpo libero','Corsa',true),
  ('Corsa calciata','Cardio','Corpo libero','Corsa',true),
  ('Ankling','Caviglia','Corpo libero','Corsa',true),
  ('Dribbling basso','Cardio','Corpo libero','Corsa',true),
  ('Dribbling medio','Cardio','Corpo libero','Corsa',true),
  ('Dribbling alto','Cardio','Corpo libero','Corsa',true),
  ('Straight-Leg Run','Cardio','Corpo libero','Corsa',true),
  ('Corsa balzata','Cardio','Corpo libero','Corsa',true),
  ('Bounding','Cardio','Corpo libero','Corsa',true),
  ('Carioca','Cardio','Corpo libero','Corsa',true),
  ('Grapevine','Cardio','Corpo libero','Corsa',true),
  ('Corsa laterale','Cardio','Corpo libero','Corsa',true),
  ('Corsa incrociata','Cardio','Corpo libero','Corsa',true),
  ('Corsa all’indietro','Cardio','Corpo libero','Corsa',true),
  ('Wall Drill','Cardio','Corpo libero','Corsa',true),
  ('Wall Switch','Cardio','Corpo libero','Corsa',true),
  ('Falling Start','Cardio','Corpo libero','Corsa',true),
  ('Lean-Fall-Run','Cardio','Corpo libero','Corsa',true),
  ('Wicket Drill','Cardio','Corpo libero','Corsa',true),
  ('Fast Leg Drill','Cardio','Corpo libero','Corsa',true),
  ('Single-Leg Cycle','Cardio','Corpo libero','Corsa',true),
  ('Pawback Drill','Cardio','Corpo libero','Corsa',true),
  ('Allunghi e accelerazioni','Atletica','Corpo libero','Forza',true),
  ('Allungo','Atletica','Corpo libero','Forza',true),
  ('Stride','Atletica','Corpo libero','Forza',true),
  ('Progressione breve','Atletica','Corpo libero','Forza',true),
  ('Accelerazione 20 metri','Atletica','Corpo libero','Forza',true),
  ('Accelerazione 30 metri','Atletica','Corpo libero','Forza',true),
  ('Accelerazione 50 metri','Atletica','Corpo libero','Forza',true),
  ('Accelerazione 80 metri','Atletica','Corpo libero','Forza',true),
  ('Accelerazione 100 metri','Atletica','Corpo libero','Forza',true),
  ('Build-Up Run','Atletica','Corpo libero','Forza',true),
  ('Ins and Outs','Atletica','Corpo libero','Forza',true),
  ('Float Sprint','Atletica','Corpo libero','Forza',true),
  ('Sprint-Float-Sprint','Atletica','Corpo libero','Forza',true),
  ('Shuttle Run','Cardio','Corpo libero','Corsa',true),
  ('Navetta 5-10-5','Cardio','Corpo libero','Corsa',true),
  ('Pro-Agility Test','Cardio','Corpo libero','Corsa',true),
  ('T-Test','Cardio','Corpo libero','Corsa',true),
  ('Illinois Agility Test','Cardio','Corpo libero','Corsa',true),
  ('L-Drill','Cardio','Corpo libero','Corsa',true),
  ('Zig-Zag Run','Cardio','Corpo libero','Corsa',true),
  ('Corsa a otto','Cardio','Corpo libero','Corsa',true),
  ('Cone Drill','Cardio','Corpo libero','Corsa',true),
  ('Box Drill','Cardio','Box/ostacoli','Corsa',true),
  ('Figure-Eight Run','Cardio','Corpo libero','Corsa',true),
  ('Carioca Drill','Cardio','Corpo libero','Corsa',true),
  ('Lateral Shuffle','Cardio','Corpo libero','Corsa',true),
  ('Crossover Run','Cardio','Corpo libero','Corsa',true),
  ('Backpedal','Cardio','Corpo libero','Corsa',true),
  ('Sprint con arresto','Cardio','Corpo libero','Corsa',true),
  ('Sprint e cambio direzione','Cardio','Corpo libero','Corsa',true),
  ('Reaction Sprint','Cardio','Corpo libero','Corsa',true),
  ('Mirror Drill','Cardio','Corpo libero','Corsa',true),
  ('Multidirectional Sprint','Cardio','Corpo libero','Corsa',true),
  ('Squat','Gambe','Corpo libero','Corsa',true),
  ('Front Squat','Gambe','Corpo libero','Corsa',true),
  ('Goblet Squat','Gambe','Corpo libero','Corsa',true),
  ('Split Squat','Gambe','Corpo libero','Corsa',true),
  ('Bulgarian Split Squat','Gambe','Corpo libero','Corsa',true),
  ('Affondi','Gambe','Corpo libero','Corsa',true),
  ('Affondi indietro','Gambe','Corpo libero','Corsa',true),
  ('Affondi camminati','Gambe','Corpo libero','Corsa',true),
  ('Step-Up','Gambe','Corpo libero','Corsa',true),
  ('Step-Down','Gambe','Corpo libero','Corsa',true),
  ('Single-Leg Squat','Gambe','Corpo libero','Corsa',true),
  ('Pistol Squat','Gambe','Corpo libero','Corsa',true),
  ('Romanian Deadlift','Gambe','Corpo libero','Corsa',true),
  ('Single-Leg Romanian Deadlift','Gambe','Corpo libero','Corsa',true),
  ('Leg Curl','Gambe','Corpo libero','Corsa',true),
  ('Nordic Hamstring Curl','Gambe','Corpo libero','Corsa',true),
  ('Calf Raise','Polpacci','Corpo libero','Corsa',true),
  ('Single-Leg Calf Raise','Polpacci','Corpo libero','Corsa',true),
  ('Soleus Raise','Cardio','Corpo libero','Corsa',true),
  ('Tibialis Raise','Caviglia','Corpo libero','Corsa',true),
  ('Toe Raise','Caviglia','Corpo libero','Corsa',true),
  ('Hip Abduction','Glutei','Corpo libero','Corsa',true),
  ('Monster Walk','Glutei','Corpo libero','Corsa',true),
  ('Lateral Band Walk','Glutei','Elastico','Corsa',true),
  ('Short Foot','Caviglia','Corpo libero','Forza',true),
  ('Toe Yoga','Caviglia','Corpo libero','Forza',true),
  ('Toe Curl','Caviglia','Corpo libero','Forza',true),
  ('Calf Raise a ginocchio esteso','Polpacci','Corpo libero','Forza',true),
  ('Calf Raise a ginocchio flesso','Polpacci','Corpo libero','Forza',true),
  ('Camminata sulle punte','Caviglia','Corpo libero','Forza',true),
  ('Camminata sui talloni','Caviglia','Corpo libero','Forza',true),
  ('Camminata sul bordo esterno del piede','Caviglia','Corpo libero','Forza',true),
  ('Equilibrio monopodalico','Caviglia','Corpo libero','Forza',true),
  ('Equilibrio monopodalico instabile','Caviglia','Corpo libero','Forza',true),
  ('Ankle Inversion con elastico','Caviglia','Elastico','Forza',true),
  ('Ankle Eversion con elastico','Caviglia','Elastico','Forza',true),
  ('Dorsiflessione con elastico','Atletica','Elastico','Forza',true),
  ('Plantarflessione con elastico','Atletica','Elastico','Forza',true),
  ('Camminata veloce','Cardio','Corpo libero','Riscaldamento',true),
  ('Jogging leggero','Cardio','Corpo libero','Riscaldamento',true),
  ('Mobilità della caviglia','Caviglia','Corpo libero','Riscaldamento',true),
  ('Mobilità dell’anca','Cardio','Corpo libero','Riscaldamento',true),
  ('Leg Swing frontale','Cardio','Corpo libero','Riscaldamento',true),
  ('Leg Swing laterale','Cardio','Corpo libero','Riscaldamento',true),
  ('Affondo dinamico','Gambe','Corpo libero','Riscaldamento',true),
  ('World’s Greatest Stretch','Cardio','Corpo libero','Riscaldamento',true),
  ('Squat dinamico','Gambe','Corpo libero','Riscaldamento',true),
  ('Allunghi progressivi','Cardio','Corpo libero','Riscaldamento',true),
  ('Camminata defaticante','Cardio','Corpo libero','Mobilità',true),
  ('Jogging defaticante','Cardio','Corpo libero','Mobilità',true),
  ('Stretching polpacci','Polpacci','Corpo libero','Mobilità',true),
  ('Stretching soleo','Caviglia','Corpo libero','Mobilità',true),
  ('Stretching quadricipiti','Cardio','Corpo libero','Mobilità',true),
  ('Stretching ischiocrurali','Cardio','Corpo libero','Mobilità',true),
  ('Stretching flessori dell’anca','Cardio','Corpo libero','Mobilità',true),
  ('Stretching glutei','Glutei','Corpo libero','Mobilità',true),
  ('Stretching adduttori','Cardio','Corpo libero','Mobilità',true),
  ('Foam Roller polpacci','Polpacci','Corpo libero','Mobilità',true),
  ('Foam Roller quadricipiti','Cardio','Corpo libero','Mobilità',true),
  ('Foam Roller ischiocrurali','Cardio','Corpo libero','Mobilità',true),
  ('Foam Roller fascia laterale della coscia','Cardio','Corpo libero','Mobilità',true),
  ('Foam Roller glutei','Glutei','Corpo libero','Mobilità',true),
  ('Respirazione diaframmatica','Cardio','Corpo libero','Mobilità',true)
ON CONFLICT DO NOTHING;

NOTIFY pgrst, 'reload schema';
